In [98]:
import pandas as pd
import re

In [99]:
df_players = pd.read_json('./Data/liga brasil/players.json')
df_players.head()

,type,href,parent,name,last_name,number,name_in_home_country,date_of_birth,place_of_birth,age,...,foot,joined,contract_expires,day_of_last_contract_extension,outfitter,current_market_value,highest_market_value,social_media,market_value_history,code
0,player,/rene/profil/spieler/212209,"{'type': 'club', 'href': '/sc-internacional-po...",,Renê,#6,None,"Sep 14, 1992","{'country': 'Brazil', 'city': 'Picos '}",31,...,left,"\n Apr 11, 2022 ...","Dec 31, 2024",NaN,adidas,NaN,NaN,[http://www.instagram.com/renerodriguees/],NaN,rene
1,player,/joao-dalla-corte/profil/spieler/1004735,"{'type': 'club', 'href': '/sc-internacional-po...",,João Dalla Corte,None,None,"Jun 7, 2006","{'country': 'Brazil', 'city': 'Encruzilhada do...",17,...,left,"\n Jan 1, 2024 ...","Dec 31, 2025",NaN,None,NaN,NaN,NaN,NaN,joao-dalla-corte
2,player,/dalbert/profil/spieler/312862,"{'type': 'club', 'href': '/sc-internacional-po...",,Dalbert,#29,None,"Sep 8, 1993","{'country': 'Brazil', 'city': 'Barra Mansa '}",30,...,left,"\n Apr 17, 2024 ...","Dec 31, 2024",NaN,None,NaN,NaN,"[http://www.facebook.com/dalbertoficial/, http...",NaN,dalbert
3,player,/felipe-motta/profil/spieler/1083638,"{'type': 'club', 'href': '/sc-internacional-po...",,Felipe Motta,#52,None,"Aug 3, 2003","{'country': 'Brazil', 'city': 'Rio de Janeiro '}",20,...,None,"\n Feb 23, 2024 ...","Jun 30, 2025",NaN,None,NaN,NaN,NaN,NaN,felipe-motta
4,player,/igor-gomes/profil/spieler/689640,"{'type': 'club', 'href': '/sc-internacional-po...",,Igor Gomes,#3,None,"Mar 6, 2001","{'country': 'Brazil', 'city': 'Barra Mansa '}",23,...,right,"\n Aug 5, 2022 ...","Dec 31, 2024",NaN,Nike,NaN,NaN,[http://www.instagram.com/01igorgomes/],NaN,igor-gomes

In [100]:
df_players['name'] = df_players['code'].str.replace('-', ' ')
df_players = df_players.drop('last_name',axis=1)
df_players = df_players.drop('code',axis=1)

In [101]:
df_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1080 entries, 0 to 1079
Data columns (total 24 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   type                            1080 non-null   object
 1   href                            1080 non-null   object
 2   parent                          1080 non-null   object
 3   name                            1080 non-null   object
 4   number                          804 non-null    object
 5   name_in_home_country            156 non-null    object
 6   date_of_birth                   1080 non-null   object
 7   place_of_birth                  1080 non-null   object
 8   age                             1080 non-null   int64
 9   height                          1028 non-null   object
 10  citizenship                     1080 non-null   object
 11  position                        1080 non-null   object
 12  player_agent                    1080 non-null   object
 13  image_url                       1080 non-null   object
 14  current_club                    1080 non-null   object
 15  foot                            1017 non-null   object
 16  joined                          1080 non-null   object
 17  contract_expires                1080 non-null   object
 18  day_of_last_contract_extension  0 non-null      float64
 19  outfitter                       590 non-null    object
 20  current_market_value            0 non-null      float64
 21  highest_market_value            0 non-null      float64
 22  social_media                    532 non-null    object
 23  market_value_history            0 non-null      float64
dtypes: float64(4), int64(1), object(19)
memory usage: 202.6+ KB

In [102]:
# Función para extraer el número de la cadena
def extraer_id_player(cadena):
    match = re.search(r'/(\d+)$', cadena)
    if match:
        return int(match.group(1))
    else:
        return None

# Aplicar la función a cada fila de la columna
df_players['player_id'] = df_players['href'].apply(extraer_id_player)
df_players.drop('href',axis=1,inplace=True)
df_players.head()

,type,parent,name,number,name_in_home_country,date_of_birth,place_of_birth,age,height,citizenship,...,foot,joined,contract_expires,day_of_last_contract_extension,outfitter,current_market_value,highest_market_value,social_media,market_value_history,player_id
0,player,"{'type': 'club', 'href': '/sc-internacional-po...",rene,#6,None,"Sep 14, 1992","{'country': 'Brazil', 'city': 'Picos '}",31,"1,74 m",Brazil,...,left,"\n Apr 11, 2022 ...","Dec 31, 2024",NaN,adidas,NaN,NaN,[http://www.instagram.com/renerodriguees/],NaN,212209
1,player,"{'type': 'club', 'href': '/sc-internacional-po...",joao dalla corte,None,None,"Jun 7, 2006","{'country': 'Brazil', 'city': 'Encruzilhada do...",17,"1,78 m",Brazil,...,left,"\n Jan 1, 2024 ...","Dec 31, 2025",NaN,None,NaN,NaN,NaN,NaN,1004735
2,player,"{'type': 'club', 'href': '/sc-internacional-po...",dalbert,#29,None,"Sep 8, 1993","{'country': 'Brazil', 'city': 'Barra Mansa '}",30,"1,81 m",Brazil,...,left,"\n Apr 17, 2024 ...","Dec 31, 2024",NaN,None,NaN,NaN,"[http://www.facebook.com/dalbertoficial/, http...",NaN,312862
3,player,"{'type': 'club', 'href': '/sc-internacional-po...",felipe motta,#52,None,"Aug 3, 2003","{'country': 'Brazil', 'city': 'Rio de Janeiro '}",20,"1,87 m",Brazil,...,None,"\n Feb 23, 2024 ...","Jun 30, 2025",NaN,None,NaN,NaN,NaN,NaN,1083638
4,player,"{'type': 'club', 'href': '/sc-internacional-po...",igor gomes,#3,None,"Mar 6, 2001","{'country': 'Brazil', 'city': 'Barra Mansa '}",23,"1,85 m",Brazil,...,right,"\n Aug 5, 2022 ...","Dec 31, 2024",NaN,Nike,NaN,NaN,[http://www.instagram.com/01igorgomes/],NaN,689640

In [103]:
# Función para extraer el número de la clave 'href'
def extraer_id_club(diccionario):
    # Utilizar una expresión regular para buscar el patrón '/verein/<número>/'
    match = re.search(r'/verein/(\d+)/', diccionario['seasoned_href'])
    if match:
        return int(match.group(1))
    else:
        return None


# Aplicar la función a cada fila de la columna 'diccionarios'
df_players['club_id'] = df_players['parent'].apply(extraer_id_club)
df_players.drop('parent',axis=1,inplace=True)
df_players.head()

,type,name,number,name_in_home_country,date_of_birth,place_of_birth,age,height,citizenship,position,...,joined,contract_expires,day_of_last_contract_extension,outfitter,current_market_value,highest_market_value,social_media,market_value_history,player_id,club_id
0,player,rene,#6,None,"Sep 14, 1992","{'country': 'Brazil', 'city': 'Picos '}",31,"1,74 m",Brazil,Defender - Left-Back,...,"\n Apr 11, 2022 ...","Dec 31, 2024",NaN,adidas,NaN,NaN,[http://www.instagram.com/renerodriguees/],NaN,212209,6600
1,player,joao dalla corte,None,None,"Jun 7, 2006","{'country': 'Brazil', 'city': 'Encruzilhada do...",17,"1,78 m",Brazil,Defender - Centre-Back,...,"\n Jan 1, 2024 ...","Dec 31, 2025",NaN,None,NaN,NaN,NaN,NaN,1004735,6600
2,player,dalbert,#29,None,"Sep 8, 1993","{'country': 'Brazil', 'city': 'Barra Mansa '}",30,"1,81 m",Brazil,Defender - Left-Back,...,"\n Apr 17, 2024 ...","Dec 31, 2024",NaN,None,NaN,NaN,"[http://www.facebook.com/dalbertoficial/, http...",NaN,312862,6600
3,player,felipe motta,#52,None,"Aug 3, 2003","{'country': 'Brazil', 'city': 'Rio de Janeiro '}",20,"1,87 m",Brazil,Defender - Centre-Back,...,"\n Feb 23, 2024 ...","Jun 30, 2025",NaN,None,NaN,NaN,NaN,NaN,1083638,6600
4,player,igor gomes,#3,None,"Mar 6, 2001","{'country': 'Brazil', 'city': 'Barra Mansa '}",23,"1,85 m",Brazil,Defender - Centre-Back,...,"\n Aug 5, 2022 ...","Dec 31, 2024",NaN,Nike,NaN,NaN,[http://www.instagram.com/01igorgomes/],NaN,689640,6600

Eliminando columnas con la totalidad de los datos nulos

In [104]:
df_players.drop('day_of_last_contract_extension',axis=1,inplace=True)
df_players.drop('market_value_history',axis=1,inplace=True)
df_players.drop('current_market_value',axis=1,inplace=True)
df_players.drop('highest_market_value',axis=1,inplace=True)
df_players.head()

,type,name,number,name_in_home_country,date_of_birth,place_of_birth,age,height,citizenship,position,player_agent,image_url,current_club,foot,joined,contract_expires,outfitter,social_media,player_id,club_id
0,player,rene,#6,None,"Sep 14, 1992","{'country': 'Brazil', 'city': 'Picos '}",31,"1,74 m",Brazil,Defender - Left-Back,"{'href': None, 'name': None}",https://img.a.transfermarkt.technology/portrai...,{'href': '/sport-club-internacional/startseite...,left,"\n Apr 11, 2022 ...","Dec 31, 2024",adidas,[http://www.instagram.com/renerodriguees/],212209,6600
1,player,joao dalla corte,None,None,"Jun 7, 2006","{'country': 'Brazil', 'city': 'Encruzilhada do...",17,"1,78 m",Brazil,Defender - Centre-Back,"{'href': None, 'name': None}",https://img.a.transfermarkt.technology/portrai...,{'href': '/sc-internacional-u20/startseite/ver...,left,"\n Jan 1, 2024 ...","Dec 31, 2025",None,NaN,1004735,6600
2,player,dalbert,#29,None,"Sep 8, 1993","{'country': 'Brazil', 'city': 'Barra Mansa '}",30,"1,81 m",Brazil,Defender - Left-Back,"{'href': None, 'name': None}",https://img.a.transfermarkt.technology/portrai...,{'href': '/sport-club-do-recife/startseite/ver...,left,"\n Apr 17, 2024 ...","Dec 31, 2024",None,"[http://www.facebook.com/dalbertoficial/, http...",312862,6600
3,player,felipe motta,#52,None,"Aug 3, 2003","{'country': 'Brazil', 'city': 'Rio de Janeiro '}",20,"1,87 m",Brazil,Defender - Centre-Back,{'href': '/promanager/beraterfirma/berater/107...,https://img.a.transfermarkt.technology/portrai...,{'href': '/emirates-club/startseite/verein/155...,None,"\n Feb 23, 2024 ...","Jun 30, 2025",None,NaN,1083638,6600
4,player,igor gomes,#3,None,"Mar 6, 2001","{'country': 'Brazil', 'city': 'Barra Mansa '}",23,"1,85 m",Brazil,Defender - Centre-Back,{'href': '/bertolucci-sports/beraterfirma/bera...,https://img.a.transfermarkt.technology/portrai...,{'href': '/sport-club-internacional/startseite...,right,"\n Aug 5, 2022 ...","Dec 31, 2024",Nike,[http://www.instagram.com/01igorgomes/],689640,6600

Eliminando columnas con datos redundantes o con direcciones web

In [105]:
df_players.drop('type',axis=1,inplace=True)
df_players.drop('player_agent',axis=1,inplace=True)
df_players.drop('image_url',axis=1,inplace=True)
df_players.drop('current_club',axis=1,inplace=True)
df_players.drop('social_media',axis=1,inplace=True)

df_players.head()

,name,number,name_in_home_country,date_of_birth,place_of_birth,age,height,citizenship,position,foot,joined,contract_expires,outfitter,player_id,club_id
0,rene,#6,None,"Sep 14, 1992","{'country': 'Brazil', 'city': 'Picos '}",31,"1,74 m",Brazil,Defender - Left-Back,left,"\n Apr 11, 2022 ...","Dec 31, 2024",adidas,212209,6600
1,joao dalla corte,None,None,"Jun 7, 2006","{'country': 'Brazil', 'city': 'Encruzilhada do...",17,"1,78 m",Brazil,Defender - Centre-Back,left,"\n Jan 1, 2024 ...","Dec 31, 2025",None,1004735,6600
2,dalbert,#29,None,"Sep 8, 1993","{'country': 'Brazil', 'city': 'Barra Mansa '}",30,"1,81 m",Brazil,Defender - Left-Back,left,"\n Apr 17, 2024 ...","Dec 31, 2024",None,312862,6600
3,felipe motta,#52,None,"Aug 3, 2003","{'country': 'Brazil', 'city': 'Rio de Janeiro '}",20,"1,87 m",Brazil,Defender - Centre-Back,None,"\n Feb 23, 2024 ...","Jun 30, 2025",None,1083638,6600
4,igor gomes,#3,None,"Mar 6, 2001","{'country': 'Brazil', 'city': 'Barra Mansa '}",23,"1,85 m",Brazil,Defender - Centre-Back,right,"\n Aug 5, 2022 ...","Dec 31, 2024",Nike,689640,6600

Eliminand columnas con datos de nula importancia

In [106]:
df_players.drop('name_in_home_country',axis=1,inplace=True)
df_players.head()

,name,number,date_of_birth,place_of_birth,age,height,citizenship,position,foot,joined,contract_expires,outfitter,player_id,club_id
0,rene,#6,"Sep 14, 1992","{'country': 'Brazil', 'city': 'Picos '}",31,"1,74 m",Brazil,Defender - Left-Back,left,"\n Apr 11, 2022 ...","Dec 31, 2024",adidas,212209,6600
1,joao dalla corte,None,"Jun 7, 2006","{'country': 'Brazil', 'city': 'Encruzilhada do...",17,"1,78 m",Brazil,Defender - Centre-Back,left,"\n Jan 1, 2024 ...","Dec 31, 2025",None,1004735,6600
2,dalbert,#29,"Sep 8, 1993","{'country': 'Brazil', 'city': 'Barra Mansa '}",30,"1,81 m",Brazil,Defender - Left-Back,left,"\n Apr 17, 2024 ...","Dec 31, 2024",None,312862,6600
3,felipe motta,#52,"Aug 3, 2003","{'country': 'Brazil', 'city': 'Rio de Janeiro '}",20,"1,87 m",Brazil,Defender - Centre-Back,None,"\n Feb 23, 2024 ...","Jun 30, 2025",None,1083638,6600
4,igor gomes,#3,"Mar 6, 2001","{'country': 'Brazil', 'city': 'Barra Mansa '}",23,"1,85 m",Brazil,Defender - Centre-Back,right,"\n Aug 5, 2022 ...","Dec 31, 2024",Nike,689640,6600

In [107]:
#Elimina la palabra 'Seats', los "." y se transofrma a entero
df_players['number'] = df_players['number'].fillna('0').str.replace('#', '').astype(int)
df_players['height'] = df_players['height'].str.replace(' m', '').str.replace('\xa0m', '').str.replace(',', '.').astype(float)
df_players['joined'] = df_players['joined'].str.strip().str.replace('-', '')
df_players['contract_expires'] = df_players['contract_expires'].str.strip().str.replace('-', '')

# Convertir la columna a formato datetime
df_players['date_of_birth'] = pd.to_datetime(df_players['date_of_birth'], format='%b %d, %Y')
df_players['joined'] = pd.to_datetime(df_players['joined'], format='%b %d, %Y')
df_players['contract_expires'] = pd.to_datetime(df_players['contract_expires'], format='%b %d, %Y')
df_players.head()

,name,number,date_of_birth,place_of_birth,age,height,citizenship,position,foot,joined,contract_expires,outfitter,player_id,club_id
0,rene,6,1992-09-14,"{'country': 'Brazil', 'city': 'Picos '}",31,1.74,Brazil,Defender - Left-Back,left,2022-04-11,2024-12-31,adidas,212209,6600
1,joao dalla corte,0,2006-06-07,"{'country': 'Brazil', 'city': 'Encruzilhada do...",17,1.78,Brazil,Defender - Centre-Back,left,2024-01-01,2025-12-31,None,1004735,6600
2,dalbert,29,1993-09-08,"{'country': 'Brazil', 'city': 'Barra Mansa '}",30,1.81,Brazil,Defender - Left-Back,left,2024-04-17,2024-12-31,None,312862,6600
3,felipe motta,52,2003-08-03,"{'country': 'Brazil', 'city': 'Rio de Janeiro '}",20,1.87,Brazil,Defender - Centre-Back,None,2024-02-23,2025-06-30,None,1083638,6600
4,igor gomes,3,2001-03-06,"{'country': 'Brazil', 'city': 'Barra Mansa '}",23,1.85,Brazil,Defender - Centre-Back,right,2022-08-05,2024-12-31,Nike,689640,6600

In [108]:
# Usar pd.json_normalize() para transformar los diccionarios en columnas
df_info = pd.json_normalize(df_players['place_of_birth'])

# Renombrar las columnas según tus necesidades
df_info.rename(columns={'country': 'country_of_birth', 'city': 'city_of_birth'}, inplace=True)

# Eliminar espacios adicionales en los valores de la columna 'city_of_birth'
df_info['city_of_birth'] = df_info['city_of_birth'].str.strip()

# Concatenar las nuevas columnas al DataFrame original
df_players = df_players.drop(columns=['place_of_birth']).join(df_info)

df_players.head()

,name,number,date_of_birth,age,height,citizenship,position,foot,joined,contract_expires,outfitter,player_id,club_id,country_of_birth,city_of_birth
0,rene,6,1992-09-14,31,1.74,Brazil,Defender - Left-Back,left,2022-04-11,2024-12-31,adidas,212209,6600,Brazil,Picos
1,joao dalla corte,0,2006-06-07,17,1.78,Brazil,Defender - Centre-Back,left,2024-01-01,2025-12-31,None,1004735,6600,Brazil,Encruzilhada do Sul
2,dalbert,29,1993-09-08,30,1.81,Brazil,Defender - Left-Back,left,2024-04-17,2024-12-31,None,312862,6600,Brazil,Barra Mansa
3,felipe motta,52,2003-08-03,20,1.87,Brazil,Defender - Centre-Back,None,2024-02-23,2025-06-30,None,1083638,6600,Brazil,Rio de Janeiro
4,igor gomes,3,2001-03-06,23,1.85,Brazil,Defender - Centre-Back,right,2022-08-05,2024-12-31,Nike,689640,6600,Brazil,Barra Mansa

In [109]:
df_players.to_csv('./Data/liga brasil/players.csv',index=False)

: